// FYEVp6I15Ua9/DUSDhG9xO/ADfYiX5BmazyjNWRLfqbxqK9j1NiL9MSqz2loTP4DnJS0CuJB2yn8lSEqa6fy9ILIE4kdeKaoDgbf2nfSe7mcSf+WFMfNpA52NYNNFe2ghOGkHRRWbL+1DxqT3Zbij8w1HxS6DlPrE8/Ted+LWz8vcxG0ROtWec9t9uqpMPbEXTmWdbyHsLwzDLx9zAtY4Xvz2ZVSA3zhcV9Z+qSOu3odiwSuP6ZC1KVFDNIbaiT54QiAPwn+BQY0lXbfhhGQlj2tjkFRn1ARXYoTFOBusg1xuYEcK71u8fBTESQfyxrgR367UN55RfHL8cVmacweog==
/**
** Copyright (C) 2000-2012 Opera Software ASA.  All rights reserved.
**
** This file is part of the Opera web browser.
**
** This script patches sites to work better with Opera
** For more information see http://www.opera.com/docs/browserjs/
**
** If you have comments on these patches (for example if you are the webmaster
** and want to inform us about a fixed site that no longer needs patching) please
** report issues through the bug tracking system
** https://bugs.opera.com/
**
** DO NOT EDIT THIS FILE! It will not be used by Opera if edited.
**/
// Generic fixes (mostly)
(function(opera){
	if(!opera || (opera&&opera._browserjsran))return;
	opera._browserjsran=true;
	var bjsversion=' Opera Mobile 12.00 core 2.10.254, July 6, 2012. Active patches: 148 ';
	// variables and utility functions
	var navRestore = {}; // keep original navigator.* values
	var shouldRestore = false;
	var hostname = location.hostname; // caching some strings for performance
	var href = location.href;
	var pathname=location.pathname;
	var fixed = false; // magic fixes need only run once
	if(!opera.postError)opera.postError=function(){}; // handling versions w/o error console
	// Storing function references
	var postError = opera.postError,
	call = Function.prototype.call,
	indexOf=String.prototype.indexOf,
	lastIndexOf=String.prototype.lastIndexOf,
	replace=String.prototype.replace,
	match=String.prototype.match,
	toLowerCase=String.prototype.toLowerCase,
	getAttribute=Element.prototype.getAttribute,
	setAttribute=Element.prototype.setAttribute,
	insertBefore=Node.prototype.insertBefore,
	insertAdjacentHTML=Element.prototype.insertAdjacentHTML,
	defineMagicVariable=opera.defineMagicVariable,
	defineMagicFunction=opera.defineMagicFunction,
	version=opera.version,
	getElementById=Document.prototype.getElementById,
	appendChild=Node.prototype.appendChild,
	removeChild=Node.prototype.removeChild,
	replaceChild=Node.prototype.replaceChild,
	evaluate=Document.prototype.evaluate,
	getElementsByTagName=Document.prototype.getElementsByTagName,
	createElement=Document.prototype.createElement,
	createEvent=Document.prototype.createEvent,
	dispatchEvent=Document.prototype.dispatchEvent,
	initEvent=Event.prototype.initEvent,
	createTextNode=Document.prototype.createTextNode,
	stopPropagation=Event.prototype.stopPropagation,
	preventDefault=Event.prototype.preventDefault,
	getComputedStyle=window.getComputedStyle,
	slice=Array.prototype.slice,
	shift=Array.prototype.shift,
	setTimeout=window.setTimeout,
	removeAttribute=Element.prototype.removeAttribute,
	addEventListener=Document.prototype.addEventListener,
	isNaN=window.isNaN,
	RegExp=window.RegExp,
	unescape=window.unescape,
	func_toString=Function.prototype.toString,
	parseFloat=window.parseFloat,
	random=Math.random;
	var opera_version = parseFloat.call(window,opera.version());
	var tinyMCEVersionInfo={};


	// Utility functions

	function addCssToDocument(cssText, doc, mediaType){
		getElementsByTagName.call=addEventListener.call=createElement.call=createTextNode.call=insertBefore.call=setAttribute.call=appendChild.call=version.call=call;
		doc = doc||document;
		mediaType = mediaType||'';
		addCssToDocument.styleObj=addCssToDocument.styleObj||{};
		var styles = addCssToDocument.styleObj[mediaType];
		if(!styles){
			var head = getElementsByTagName.call(doc, "head")[0];
			if( !head ){
				var docEl = getElementsByTagName.call(doc, "html")[0];
				if(!docEl){
					// :S this shouldn't happen - see if document hasn't loaded
					addEventListener.call(doc, opera&&version.call(opera)>=9?'DOMContentLoaded':'load',
					function(){ addCssToDocument(cssText, doc); },false);
					return;
				}
				head = createElement.call(doc, "head");
				if(head) insertBefore.call(docEl, head,docEl.firstChild);
				else head = docEl;
			}
			addCssToDocument.styleObj[mediaType] = styles = createElement.call(doc, "style");
			setAttribute.call(styles, "type","text/css");
			if(mediaType)setAttribute.call(styles, "media", mediaType);
			appendChild.call(styles, createTextNode.call(doc,' '));
			appendChild.call(head, styles)
		}
		styles.firstChild.nodeValue += cssText+"\n";
		return true;
	}

	function addPreprocessHandler( search, replacement, onceonly, conditional ){
		// adding event handler for script pre-processing if required
		var handler=function(e){
			indexOf.call=replace.call=removeEventListener.call=call; /* also needs anything used inside conditional! */
			if( conditional && ! conditional(e.element) ){return;}
			e.element.text=replace.call( e.element.text, search, replacement );
			if(onceonly){
				removeEventListener.call(opera, 'BeforeScript', arguments.callee, false);
			}
		}
		opera.addEventListener('BeforeScript', handler , false);
		return handler;
	}

function avoidDocumentWriteAbuse(contentRegexp){
	var dw=document.write;
	contentRegexp = contentRegexp || /(^<img .*?width=("|)1("|)\s+height=("|)1("|)\s+border=("|)0("|)\s+alt="".*?>$|^\[object Object\]$)/i;
	document.write=function( s ){
		if( String(s).match( contentRegexp ) ){
			opera.postError('Warning: scripts on '+window.location+' were changed by the s_code patch. See browser.js for details.');
		}else{//opera.postError(arguments);
			dw.apply(document, arguments);
		}
	};
}
function fixGawkerMobile() {
	addCssToDocument('.non_webkit #comments, .non_webkit #comment_controls { display: block !important; }'
		+'#i_home .icon.icon29{background-position:0 -120px}'
		+'#i_home .selected .icon.icon29{background-position:-29px -120px}'
		+'#i_popular .icon.icon29{background-position:0 -149px}'
		+'#i_popular .selected .icon.icon29{background-position:-29px -149px}'
		+'#i_search .icon.icon29{background-position:0 -178px}'
		+'#i_search .selected .icon.icon29{background-position:-29px -178px}'
		+'#i_account .icon.icon29{background-position:0 -207px}'
		+'#i_account .selected .icon.icon29{background-position:-29px -207px}'
		+'#nav_home .icon.icon29{background-position:0 -120px}'
		+'#nav_home .selected .icon.icon29{background-position:-29px -120px}'
		+'#nav_top .icon.icon29{background-position:0 -265px}'
		+'#nav_top .selected .icon.icon29{background-position:-29px -265px}'
		+'.icon {background-size: 62px 370px !important;}'
	);
}
function forceMobileView(){
if( document.documentElement ){
	var meta=document.documentElement.appendChild(document.createElement('meta'));
	meta.setAttribute('name', "viewport");
	meta.setAttribute('content', "width=device-width,user-scalable=no");
}}

function forceWordWrapping(wrapTargets) {
    var wrapElements = wrapTargets||'div, span, p, li, a, td, th';
    opera.postError('Warning: Browser has forced word wrapping for certain elements.');
    addCssToDocument(wrapElements + '{ white-space: -o-pre-wrap !important; }')
}
function prepareFakeDesignMode(){
	document.addEventListener('load', function(e){
		try{
		if( e.target.tagName == 'IFRAME' ){
			// avoid security policy problems when document.domain is set
			if(hostname!=document.domain){
				var crossDomainPolicyBug=false;
				try{
					e.target.contentDocument.body;
				}catch(e){
					crossDomainPolicyBug=true;
				}
			    if(e.target.src=='' && crossDomainPolicyBug){
				e.target.src='data:text/html,"<script>document.domain=\''+document.domain+'\';</script>"';
			    }
			}
			if( e.target.contentDocument.designMode=='on' ){
				fakeDesignMode(e.target.contentDocument);
			}
			e.target.contentDocument.__defineSetter__('designMode', function(v){
				if(/on/i.test(v)){
					fakeDesignMode(this);
				}
			});
		}
		}catch(e){ opera.postError(e); }
		function fakeDesignMode(doc){
			var txt=doc.body.appendChild(doc.createElement('textarea'));
			txt.setAttribute('style', 'width:100%;height:100%;position:absolute;top:0;left:0;right:0;bottom:0')
			doc.body.style.overflow='hidden';
			txt.value=doc.body.innerText;
			doc.execCommand=function(){};
			doc.body.__defineGetter__('innerHTML', function(){ return txt.value.replace(/\n/g, '<br>\n'); });
			doc.body.__defineSetter__('innerHTML', function(v){ txt.value=v.replace(/<[^<]+>/g, ' ').replace( / {2,}/,' ' ); });
			doc.documentElement.__defineGetter__('innerHTML', function(){ return txt.value.replace(/\n/g, '<br>\n'); });
			doc.documentElement.__defineSetter__('innerHTML', function(v){ txt.value=v.replace(/<[^<]+>/g, ' ').replace( / {2,}/,' ' ); });
			doc.body.__defineGetter__('innerText', function(){ return txt.value; });
			doc.body.__defineGetter__('textContent', function(){ return txt.value; });
			doc.open=doc.defaultView.focus=function(){txt.focus();};
			doc.write=function(){
				txt.value=arguments.join('').replace(/<style.*\/style>/ig, '').replace(/<[^>]*>/g, ' ').replace(/&quot;/g, '"').replace(/\s{1,}/g, ' ');
			};
		}
	}, true);
}
function scaleImagesToScreenWidth(maxWidth) {
    var max = maxWidth || screen.width;
    addCssToDocument('img { max-width: ' + max + 'px !important; height: auto !important; }');
    opera.postError('Warning: Image resized to screen width by browser. See browser.js for details.');
}
function stopKeypressIfDownCancelled(stopKey){
	opera.addEventListener('AfterEventListener.keydown', function(e){
		if(e.eventCancelled)stopKey=true;
	}, false);

	opera.addEventListener('BeforeEvent.keypress', function(e){
		if(stopKey){
			preventDefault.call=call;
			preventDefault.call(e.event);
			stopKey=false;
		}
	}, false);
}




	// Prototype requires function.toString to return a unique string per function
// Work around browser sniffing in old Macromedia menu script
// Replace Youtube embeds with image and link on Android devices with no plugins.
// Generic prepareFakeDesignMode
// Compatibility layer for Google Gears initialization script
// Handle s_code stats script not named s_code - prevent them overwriting documents
// Asia-region Generic Patches
// Generic patches (Windows mobile)
// Work around Facebook's attachEvent usage in all.js
// Make sure plugin sniffers detect the correct Flash API version
// Make getUserMedia() scripts written according to current spec work
// Generic key event patch for better spatnav
			// 272007, Prototype requires function.toString to return a unique string per function
	var funcCount=0;
	if((function(){}).toString().indexOf('ecmascript code')!=-1)Function.prototype.toString=function(){
		if(!this.functionNumber){
			this.functionNumber = funcCount;
			funcCount++;
		}
		return 'function func'+this.functionNumber+'(){[ecmascript code]}';
	}
			// PATCH-621, Work around browser sniffing in old Macromedia menu script
	opera.defineMagicFunction('mmLoadMenus', function(func, context){
	  window.__defineSetter__('mmIsOpera', function(){});
	  window.__defineGetter__('mmIsOpera', function(){return false});
	  return func.apply(context, Array.prototype.slice.call(arguments, 2));
	});
	
			// ANDMO-1210, Replace Youtube embeds with image and link on Android devices with no plugins.
	document.addEventListener("DOMContentLoaded", function (e) {
		if( navigator.platform == "Android" && !navigator.plugins.length ){
			var nodes = document.selectNodes('//object[starts-with(@data,"http://www.youtube.com/v/")] | //object//param[starts-with(@name,"src") and starts-with(@value,"http://www.youtube.com/v/")] | //embed[starts-with(@src,"http://www.youtube.com/v/")]');	
			for ( var i = nodes.length-1; i >= 0 ; i-- ) {	
				var id;
				var element = nodes[i];
				var uri = document.createElement('a');
				uri.href = (element.src) ? element.src : (element.data) ? element.data : (element.value) ? element.value : "";
				id = (uri.pathname.match(/embed\//)) ?  uri.pathname.split(/embed\//)[1] : uri.pathname.split(/v\//)[1];		
				id = id.split(/&/)[0];
				var VidUrl = document.createElement('a');
				VidUrl.href = "vnd.youtube:" + id;
				var ThumbImage= document.createElement('img');
				ThumbImage.src = "http://img.youtube.com/vi/"+id+"/1.jpg";
				ThumbImage.width = (element.width) ? element.width : element.parentNode.width;
				ThumbImage.height = (element.height) ? element.height : element.parentNode.height;	
				VidUrl.appendChild(ThumbImage);
				element.parentNode.replaceChild(VidUrl, element);
			}
		 }
	}, false);
			// PATCH-16, Generic prepareFakeDesignMode
	if(location.protocol=='https:'||location.protocol=='http:')prepareFakeDesignMode()
			// 347496, Compatibility layer for Google Gears initialization script
	if (window.opera && opera.createWorkerPool && 
	    navigator.mimeTypes["application/x-googlegears"] &&
	    navigator.mimeTypes["application/x-googlegears"].enabledPlugin
	    ){
		window.GearsFactory = function()
		{
		    var element = document.createElement("object");
		    element.setAttribute('style', 'display:block;width:1px;height:1px;position:absolute;left:-2px');
		    element.type = "application/x-googlegears";
	 
		    document.documentElement.insertBefore(element,
							  document.documentElement.firstChild);
		    element.getBuildInfo(); // to make sure init is complete
		    return element;
		}
	}
			// EMO-5081, Handle s_code stats script not named s_code - prevent them overwriting documents
	opera.defineMagicVariable('s_account', null, function(obj){ avoidDocumentWriteAbuse(); return obj; });
			// PATCH-138, Asia-region Generic Patches
	opera.addEventListener('BeforeExternalScript',function(ev){
		var name=ev.element.src; 
		if(!name){return;}
		if(name.indexOf('api.e-map.ne.jp/jsapi.cgi?')!=-1){
			// Zenrin Datacom E-Map API, PATCH-115
			if (!Event.prototype.__lookupGetter__('layerX')&&!Event.prototype.__lookupGetter__('layerY')) {
				Event.prototype.__defineGetter__('layerX',function(){ return this.offsetX; });
				Event.prototype.__defineGetter__('layerY',function(){ return this.offsetY; });
			}
			ev.element.src += '&force=1';
		}else if((name.indexOf('expapi/authentication')!=-1)||(name.indexOf('expapi/expmapinclude')!=-1)||(name.indexOf('rosen/authentication')!=-1)){
			// Rosenzu ASP Map Service map, PATCH-122
			opera.defineMagicFunction('_ch',function(){return true;});
		}else if((name.indexOf('expapi/suggest')!=-1)||(name.indexOf('rosen/suggest')!=-1)){
			// Rosenzu ASP Map Service suggestions, PATCH-122
			opera.defineMagicFunction('checkBrowser',function(){return true;});
		}else if(name.indexOf('http://ebook.webcatalog.jp/engine/java/7net/common/sCommonLib.js')!=-1){ 
			// Netfly TrueEBook, PATCH-125
			opera.defineMagicFunction('funcGetBrowser',function(){return 2;}); 
		}else if(name.indexOf('_zap/')!=-1 && name.indexOf('source/js/script.js')!=-1){ 
			// ZAPPALLAS Fortune _zap, PATCH-471
			opera.defineMagicFunction('checkNavigator',function(){return true;}); 
		}
	},false);
			// 0, Generic patches (Windows mobile)
	// Use an event listener to detect specific scripts
	opera.addEventListener( 'BeforeExternalScript', function(ev){
		match.call=replace.call=indexOf.call=toLowerCase.call=postError.call=addEventListener.call=removeEventListener.call=version.call=parseFloat.call=call;
		var name=ev.element.src; 
		if( !name ){ return; } // no fixes required for SCRIPT xlink:href so far..
		name=toLowerCase.call(name );// toLowerCase fixes sangjatten.se
		if(indexOf.call(name,'s_code')>-1||indexOf.call(name,'omniture')>-1){//PATCH-59
			avoidDocumentWriteAbuse();
		}if(indexOf.call(name, 'zshare.net/videoplayer/js/PlayerFunctions.js')>-1){ // SOKRI4-1002
			opera.defineMagicFunction( 'hide_ad', function( rf, rt ){
				if( document.player )document.player.style.visibility='visible';
				return rf.apply(rt, slice.call(arguments, 2)) }
			);
			opera.defineMagicFunction( 'show_ad', function( rf, rt ){
				if( document.player )document.player.style.visibility='hidden';
				return rf.apply(rt, slice.call(arguments, 2)) }
			);
		}
	}, false);
			// PATCH-372, Work around Facebook's attachEvent usage in all.js
	opera.addEventListener( 'BeforeExternalScript', function(ev){
		indexOf.call=addEventListener.call=removeEventListener.call=call;
		
		var name=ev.element.src;
		if(indexOf.call(name,'connect.facebook.net')>-1 && indexOf.call(name,'all.js')>-1){ //PATCH-372, PATCH-386
			var win_attachEvent=window.attachEvent;
			document.attachEvent=undefined; //PATCH-576
			var ifrScrollingSetter = (document.createElement('iframe')).__lookupSetter__('scrolling');
			var ifrScrollingGetter = (document.createElement('iframe')).__lookupGetter__('scrolling');
			HTMLIFrameElement.prototype.__defineSetter__('scrolling', function(){ if(this.src=='')this.src='javascript:void(0);'; return ifrScrollingSetter.apply(this,arguments); });
			HTMLIFrameElement.prototype.__defineGetter__('scrolling', function(){ return ifrScrollingGetter.apply(this,arguments); });
	
			if( window.fbAsyncInit && !window.fbAsyncInit._patched ){
				var origFBAsyncInit=window.fbAsyncInit;
				window.fbAsyncInit=function(){
					window.attachEvent=undefined;
					origFBAsyncInit.call(null);
					window.attachEvent=win_attachEvent;
				}
				window.fbAsyncInit._patched=true;
			}else{
				window.attachEvent=undefined; 
				addEventListener.call(opera, 'AfterScript', function(e){
					if( window.FB && FB.init && ! FB.init._patched ){
						(function(init){
							FB.init=function(){
								window.attachEvent=undefined;
								init.apply(this,arguments);
								window.attachEvent=win_attachEvent;
							}
						})(FB.init);
						FB.init._patched=true;
					}
					window.attachEvent=win_attachEvent;
					removeEventListener.call(opera, 'AfterScript', arguments.callee, false);
				}, false);
			}
		}
	
	},false);
			// PATCH-4, Make sure plugin sniffers detect the correct Flash API version
	if( opera.flashPluginAX && opera.flashPluginAX() && Object.prototype.__defineGetter__ ){
		var origPluginGetter = navigator.__lookupGetter__('plugins');
		navigator.__defineGetter__('plugins', function(){
			try{
				new ActiveXObject('ShockwaveFlash.ShockwaveFlash.6');
				return undefined;
			}catch(e){
				return origPluginGetter.call(this);
			}
		});
	};
			// PATCH-581, Make getUserMedia() scripts written according to current spec work
	if( navigator.getUserMedia ){
		if( ! window.URL )window.URL={};
		if( ! window.URL.createObjectURL)window.URL.createObjectURL=function(obj){return obj;}
	}
			// PATCH-369, Generic key event patch for better spatnav
	stopKeypressIfDownCancelled();
	


	if((hostname.indexOf('tokyo.jp')>-1)||(hostname.indexOf('lg.jp')>-1)){			// PATCH-186, tokyo.jp, lg.jp enable maps
		if (location.pathname.indexOf('citymap')>-1) {
			window.opera.defineMagicFunction('chkBrowser',function(){
				return true;
			},false);
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (tokyo.jp, lg.jp enable maps). See browser.js for details');
	} else if(hostname.indexOf( '.56.com' )>-1){			// YUSHAN-232, Fix search button position issues for 56.com
		addCssToDocument(".so {background-color:transparent !important;} .search .so .so_input .inp_search{ width:232px !important; } ");
				// YUSHAN-233, Fix hyperlinks position issue of 56.com
		addCssToDocument(".chn_nav { white-space:nowrap !important; }");
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix search button position issues for 56.com\nFix hyperlinks position issue of 56.com). See browser.js for details');
	} else if(hostname.indexOf( 'bbc.co.uk' )>-1){			// YUSHAN-226, Fix page footer text overlap issue for bbc.co.uk
		addCssToDocument(" #disclaimer { bottom: 6px !important; white-space:nowrap; } ");
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix page footer text overlap issue for bbc.co.uk). See browser.js for details');
	} else if(hostname.indexOf( 'windowsmedia.com' )!=-1 && pathname.match( /^\/mobile\// )){			// OSAN-91, Mobile Windowsmedia site does not trigger mobile view
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Mobile Windowsmedia site does not trigger mobile view). See browser.js for details');
	} else if(hostname.indexOf("lotteimall.com")>-1){			// SEOUL-607, fixes a spurious alert on lotteimall.com
		var old_alert = alert;
		
		window.alert = function(e) {
		  if(e.indexOf('flashVer=') == -1) {
		    old_alert(e);
		  }
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (fixes a spurious alert on lotteimall.com). See browser.js for details');
	} else if(hostname.indexOf('.ebay.')>-1 || hostname.indexOf('.ebaydesc.')>-1){			// 0, eBay
		/* eBay issues */
	
	
		if(hostname.indexOf('my.ebay.')>-1){			// EMO-4726, Fix broken layout in ebay inbox
			addCssToDocument('#msgTable,#scrDiv,#wrapperrcp{width: auto !important}');
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix broken layout in ebay inbox). See browser.js for details');
		}
		if(hostname.indexOf('wap.ebay.cn')>-1){			// PNGLAI-704, Avoid overlap
			addCssToDocument('h2 {min-height: 22px; height: auto !important;}');
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Avoid overlap). See browser.js for details');
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (eBay). See browser.js for details');
	} else if(hostname.indexOf('.evaair.com')>-1){			// PATCH-688, evaair.com: broken sniffing
		navigator.appName='Netscape';
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (evaair.com: broken sniffing). See browser.js for details');
	} else if(hostname.indexOf('.google.')>-1){			// 0, Google
		/* Google */
	
	
		if(hostname.indexOf('mail.google.')>-1){			// SOKRI4-171, GMail detects mobile version as desktop version if opera.version() says 9.5
			window.opera.version = opera.version = function() { return 0; }
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (GMail detects mobile version as desktop version if opera.version() says 9.5). See browser.js for details');
		}
		if(hostname.indexOf('www.google.com')!=-1&&pathname.indexOf('/m')==0&&pathname.indexOf('/mail')==-1){			// UMAFINAL-719, On narrow screens Google's navigation bar can wrap and cause overlap
			addCssToDocument('.navbar { height: auto; !important; }');
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (On narrow screens Google\'s navigation bar can wrap and cause overlap). See browser.js for details');
		}
		if(href=="http://www.google.com.tw/"){			// UMAFINAL-534, Autocomplete makes typing very slow on google.com.tw
			(function(){
			    opera.addEventListener('BeforeEventListener.keyup', function(e) {
			        if(e.event.target.name=='q') e.preventDefault();
			    }, false);
			    opera.addEventListener('BeforeEventListener.keydown', function(e) {
			        if(e.event.target.name=='q') {e.preventDefault();}
			    }, false);
			    var setInt=window.setInterval;
			    setInterval=function(func,time){
				if( time==10 )time=2000;
				setInt.call(this, func,time);
			    };
			    })();
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Autocomplete makes typing very slow on google.com.tw). See browser.js for details');
		}
		if(pathname.indexOf('/m')==0&&pathname.indexOf('mail')==-1){			// SOKRI3-1403, Google Mail navigation bar overlaps if localised text is too long
			addCssToDocument('.navbar { height: auto; !important; }');
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Google Mail navigation bar overlaps if localised text is too long). See browser.js for details');
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Google). See browser.js for details');
	} else if(hostname.indexOf('.usps.com')>-1){			// PATCH-718, USPS: work around old browser sniff
		opera.defineMagicVariable('browserSupported',function(){return true},null);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (USPS: work around old browser sniff). See browser.js for details');
	} else if(hostname.indexOf('.yahoo.')>-1){			// 0, Yahoo!
		/* Yahoo! */
	
	
		if(hostname.indexOf('finance.yahoo.com')>-1){			// PATCH-406, Prevent currency menu from closing too fast on Y!Finance
			opera.addEventListener('BeforeEventListener.focusout', function(e){e.preventDefault();}, false);
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Prevent currency menu from closing too fast on Y!Finance). See browser.js for details');
		}
		if(hostname.indexOf('mail')==-1){			// 252519, Prevent page from focusing search field because it causes unexpected scrolling
			opera.addEventListener('AfterEventListener.load',
			function(){ try{ document.sf1.p.focus=function(){}; }catch(e){}},false);
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Prevent page from focusing search field because it causes unexpected scrolling). See browser.js for details');
		}
		if(hostname.indexOf('mail.yahoo.')!=-1){			// UMAFINAL-1264, Fake designmode for Yahoo mail
			prepareFakeDesignMode();
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fake designmode for Yahoo mail). See browser.js for details');
		}
		if(hostname=='new.m.yahoo.com'){			// OSAN2-281, Banner image goes over screen width on new.m.yahoo.com
			scaleImagesToScreenWidth(); 
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Banner image goes over screen width on new.m.yahoo.com). See browser.js for details');
		}
		if(href=="http://www.tw.yahoo.com/"){			// UMAFINAL-534, Autocomplete makes typing very slow on www.tw.yahoo.com
			opera.addEventListener('BeforeEventListener.keyup', function(e) {
			    if(e.event.target.name=='q') e.preventDefault();
			}, false);
			opera.addEventListener('BeforeEventListener.keydown', function(e) {
			    if(e.event.target.name=='q') {e.preventDefault();}
			}, false);
				if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Autocomplete makes typing very slow on www.tw.yahoo.com). See browser.js for details');
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Yahoo!). See browser.js for details');
	} else if(hostname.indexOf('.youtube.com')>-1){			// JOZO81-2229, Make sure all thumbnails on youtube are visible, even in zoomed out mode
		window.__defineGetter__('innerHeight', function(){ return Math.max(document.documentElement.offsetHeight, document.body.offsetHeight, document.documentElement.scrollHeight); });
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Make sure all thumbnails on youtube are visible, even in zoomed out mode). See browser.js for details');
	} else if(hostname.indexOf('10.235.148.9')>-1){			// HMONY-1927, Remove overlapping text on vnet.mobi
		if( document.documentElement ){ 
		 var meta=document.documentElement.appendChild(document.createElement('meta')); 
		 meta.setAttribute('name', "viewport"); 
		 meta.setAttribute('content', "width=340,user-scalable=no");
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Remove overlapping text on vnet.mobi). See browser.js for details');
	} else if(hostname.indexOf('10086.cn')>-1){			// NHSP-427, Fix layout broken issue of CMCC mobile page
		if(pathname.indexOf('m')>-1 && pathname.indexOf('service')>-1 ) {
		   //NHSP-427
		   addCssToDocument('.sel_001 li dd { height: auto !important; min-height: 140px;  } #header {white-space: nowrap;}');
			function addViewport() {
				var meta;
				if (document.createElement && (meta = document.createElement('meta'))) {
						meta.name = "viewport";
						meta.content = "width=device-width, initial-scale=1.0, maximum-scale=3.0, user-scalable=yes";
						document.getElementsByTagName('head')[0].appendChild(meta);
				}	
			}
			
			//<meta name="viewport" content="width=device-width, initial-scale=1.4, minimum-scale=1.0, maximum-scale=2.0"/>
			function setViewport(){
				//Remove iframe disturbance
				var docT = document;
				var eiFrame = docT.getElementsByTagName('iframe');
				if(eiFrame) {
					for(var i=0; i<eiFrame.length; i++) {
						eiFrame[i].parentNode.removeChild(eiFrame[i]);	
					}
				}
				
				var eMeta = docT.getElementsByTagName('meta');
				
				if(eMeta){
					for(var i=0; i<eMeta.length; i++){
						if(eMeta[i].getAttribute('name')){
							if(eMeta[i].getAttribute('name').toLowerCase()=='viewport') {
								eMeta[i].parentNode.removeChild(eMeta[i]);
							}
						}
					}
					addViewport();
				}
				else {
					addViewport();	
				}
			}	   
		   document.addEventListener("DOMContentLoaded", setViewport,false);
		}
		
				// YUSHAN-2359, Fix zoom issue of 10086.cn (cmcc portal)
		if(location.pathname.indexOf('m') >-1)
		      {  
			function ModifyViewportInitialScale()
			{
			   var eMeta = document.getElementsByTagName('meta'); 
			   if(eMeta)
			   { 
			      for(var i=0; i<eMeta.length; i++)
			      { 
			         if(eMeta[i].getAttribute('name'))
			         { 
			            if(eMeta[i].getAttribute('name').toLowerCase()=='viewport')
			            { 
			               var eViewportContent = eMeta[i].getAttribute('content'); 
			               
			               // To force use initial-scale=1.0 
			               if(eViewportContent.indexOf('initial-scale')>-1)
			               { 
			                  var reg = /initial-scale=[^,;]*[,;]/; 
			                  eViewportContent=eViewportContent.replace(reg,"initial-scale=1;"); 
			               } 
			               
			               eMeta[i].setAttribute('content',eViewportContent);
			            } 
			         } 
			      } 
			   } 
			}
		         ModifyViewportInitialScale(); 
		      } 
				// YUSHAN-3557, Fix page footer display issue of 10086.cn/m
		if(pathname.indexOf('m') >-1){
		      addCssToDocument("#footer {min-width: 400px; background-color: #25557E !important; min-height: 38px; height: auto !important;} #footer li {line-height: normal;}"); 
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix layout broken issue of CMCC mobile page\nFix zoom issue of 10086.cn (cmcc portal)\nFix page foot...). See browser.js for details');
	} else if(hostname.indexOf('11st.co.kr')>-1){			// DONGDAE-4055, Ignore popunder
		opera.defineMagicFunction('openMainPopunder',function(){});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Ignore popunder). See browser.js for details');
	} else if(hostname.indexOf('163.com')>-1){			// NHSP-416, Wrong page layout display of 163.com touch version
		if(hostname.indexOf('3g.')>-1 ) {
		  if(pathname.indexOf('touch')>-1 ) {
			addCssToDocument('#mask { height: 0px !important; }');
		  }
		}
				// NHSP-403, Log in page display issue of smart.mail.163.com
		if(hostname.indexOf('mail.')>-1 && hostname.indexOf('smart.')>-1) {
			addCssToDocument('.mod-login .loginBtn { -o-border-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAqCAYAAABhqXGIAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAwMS8wNy8xMUth1boAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzQGstOgAAACLUlEQVQ4jYWUX08TQRTFf3d2tlsQG4r8E4P/0Cc/gokPvPtg/JTEr6AhMRI/gPpEQkhMpDUthRQo7e7e68PS2d1ScJN52MmZc869587Il8O+AVxcTTj42aEzuGZ9OeHtm01aSwkAToDB+Yi9/SOurMmLnWdM3CJ7+0d0Ty8QwJkq3391WV1/xMbGCucTWFtrs7m1zsGPLprnuFwzfvcuabdb9C4zJpnSGaa02y1OTkdkeYZXhUlqOOeYpCkARvGJOMap4s2M6pp+4d8MTwWgc0BmhpfphiqmWoJUMTME8OGUFqsElfIeQNVQ6nKKoVoBlUx6B5MQADrrSQ0LcqaolfTFnqGmgP1fLlSnd8jVjavNlbMqqADUmVQ1tMSDBOo6aOpRSiasHgs3FWPgRQgst+TUEAnG75OrGDetVzetOHS82JiRM51pwT2eKnLFKc3rsYTshHIKbk2mVrO7iaQWi1q149Xsqsar2cl0Y84U1Jl0/r2rNtPumIIw44IUEdjMZIb5kvr4zsZSu3f3vgW1Ps3J7lafigekykTokxMRktiRpTmxkyIKA82LLOM4wjkHr7aX6Q+GbK0s0vCOp2sP6A+GPH/cohFHOHGO9+9e0uud86d7xurDBp2/Z/zp9Pmwu4Nzgnw9OrXxaMRJt8enz4ccnwzZ3lji4+5rtp+s0mwuIN+Oz0zznMl4zPX1FVma4WNPkizQSBIi74vqXBTRaDaJYo+pIs4RRb4wDPwDulhjLyjShpEAAAAASUVORK5CYII=) 0 4 0 4 stretch stretch;  } .mod-login .iptBox { background-color: #fff;} ');
		}
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Wrong page layout display of 163.com touch version\nLog in page display issue of smart.mail.163.com). See browser.js for details');
	} else if(hostname.indexOf('218.206.177.209')>-1){			// YUSHAN-3774, Fix pop up issue of  CMCC IOT test
		if(pathname.indexOf('waptest')>-1) {
		  addPreprocessHandler('history.back()', 'location.href="pass.htm"; window.open("mytest.html");' );
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix pop up issue of  CMCC IOT test). See browser.js for details');
	} else if(hostname.indexOf('3g.qq.com')>-1){			// OMO-408, Fix element shows abnormally issue of 3g.qq.com
		if (hostname.indexOf('info') > -1 && pathname.indexOf('/g/s')==0) {
		 addCssToDocument('.stock, .img-news{float:left;} .stock-up-num, .stock-down-num, .marquee {float:right;} .t-center {display: inline-block; margin-left:2px; margin-right:2px;} #div_live_content > a {font-size:12px; !important; } .qq-product a  {display: inline-block !important;} .main-nav-list li, .main-nav-list li a { display:inline-block !important; }'); 
		 opera.addEventListener('BeforeCSS', function(userJSEvent){ userJSEvent.cssText = userJSEvent.cssText .replace(/-(webkit)-(background-size)/g,'$2'); }, false);
		}
				// NHSP-417, Broken layout on stock page in 3g.qq.com
		if(hostname.indexOf('gp.') >-1) {
		  addCssToDocument('.submit {background-color:#48629D; }  .txt-input {width: auto !important;} .stock-list li { padding: 6px 6px; float: left; } .stock-list li:nth-last-child(3), .img-slide { clear:both; } ');
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix element shows abnormally issue of 3g.qq.com\nBroken layout on stock page in 3g.qq.com). See browser.js for details');
	} else if(hostname.indexOf('3g.sina.com.cn')>-1){			// OMO-103, Fix searchbox display issue of sina iAsk (webkit)
		if(pathname.indexOf('/iask/')==0)
		{   
		    addCssToDocument('#toolbar .osContainer {width:90% !important; } #main h2.hd {padding: 0 !important; background: -o-linear-gradient(#FFFFFF,#E9E9E9) !important;} #main h2.hd > .title span {margin-left:8px !important;}');
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix searchbox display issue of sina iAsk (webkit)). See browser.js for details');
	} else if(hostname.indexOf('addynamix.com') > -1){			// SEOUL-601, Fixes panning on addynamix.com
		addCssToDocument('#main {overflow: visible;}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fixes panning on addynamix.com). See browser.js for details');
	} else if(hostname.indexOf('aeonretail.jp')>-1){			// PATCH-88, Make links work on Aeonretail (outdated jQuery plugin detects Opera and scrolls up)
		addPreprocessHandler(/var el = win \? \$\.browser\.opera \? document\.body : document\.documentElement : elem;/, 'var el = win ? document.documentElement : elem;', true, function(elm){ return elm.src&&elm.src.indexOf('scroll.js')>-1&&elm.text.indexOf('Opera 9.22')>-1; });
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Make links work on Aeonretail (outdated jQuery plugin detects Opera and scrolls up)). See browser.js for details');
	} else if(hostname.indexOf('athome.co.jp') > -1){			// PATCH-147, athome.co.jp Hide warning messages because of Browser UA
		opera.defineMagicFunction('checkTargetBrowser',function(){});
		opera.defineMagicFunction('checkTargetCookie',function(){});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (athome.co.jp Hide warning messages because of Browser UA). See browser.js for details');
	} else if(hostname.indexOf('autohome.com.cn')>-1){			// OMO-345, Images loading issue on autohome.com.cn
		function lazyloadiframe_replace(real, thisObject, oParam1, oParam2)
		{
		    oParam1.readyState = "complete";
		    oParam2 = true;
		    return real(oParam1, oParam2);
		};
		
		window.opera.defineMagicFunction('lazyloadIframe', lazyloadiframe_replace);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Images loading issue on autohome.com.cn). See browser.js for details');
	} else if(hostname.indexOf('baidu.com')>-1){			// YUSHAN-3971, Fix search result page display issue of baidu.com
		if(hostname.indexOf('www.') >-1 && href.indexOf('s?') > -1){
		      addCssToDocument("#head form, #search form { white-space: nowrap !important; }");
		}
				// YUSHAN-2320, Fix links display inside searchbox - image.baidu.com
		if(hostname.indexOf('image.')>-1){
		addCssToDocument(" #kw{width:200px !important;  } #l, #nv { width: auto !important; text-indent: 0px !important; text-align:center; }  form[name=f], form[name=f1], #nv, #l {white-space:nowrap; } #mCon { display:none;} ");
		}
				// NHSP-402, Fix image display issue on baidu news
		if(hostname.indexOf('wap.') >-1 || hostname.indexOf('m.') >-1 || hostname.indexOf('gate.') >-1) {
		 if(pathname.indexOf('news')>-1 || location.search.indexOf('news')>-1) {
		  var iWidth = window.innerWidth;
		  iWidth = iWidth - 20; 
		  addCssToDocument('p img, div img { max-width:'+ iWidth +'px !important; }');
		 } 
		}
				// YUSHAN-278, Text truncation in blog/forum module - news.baidu.com
		if(hostname.indexOf( 'news.baidu.com' )>-1){
		  addCssToDocument(".hotwords dd br {height:0px !important;line-height:0px !important; } .hotwords dd a { font-size:12px !important; }");
		}
		
				// OMO-102, Fix "more" link issue of m.baidu.com
		if( (hostname.indexOf('m.baidu.com') > -1  && pathname.indexOf('/ssid=') > -1 ) || //news
		    (hostname.indexOf('m.baidu.com') > -1  && pathname.indexOf('/img') > -1 ) || //image
		    (hostname.indexOf('m.baidu.com') > -1  && pathname.indexOf('/video') > -1 ) || //image
		    hostname.indexOf('wapiknow.baidu.com') > -1 ||
		    hostname.indexOf('wapbaike.baidu.com') > -1 ||
		    hostname.indexOf('news.baidu.com') > -1 ||
		    hostname.indexOf('wk.baidu.com') > -1
		)
		{   
		    opera.addEventListener('AfterEvent.DOMContentLoaded', function(userJSEvent){
		        var B = getElementById("o_more");
		        var E = getElementById("o_body");
		        var F = getElementById("o_list");
		        // alert("B="+ B + "E=" + E + "F=" + F);
		        if (B && E && F) B.addEventListener("click",
		          function(_) {
		            // alert("sldjf");
		            if (!E.style.display || E.style.display == "none") {
		                var $ = document.body.offsetHeight;
		                E.style.width = "100%";
		                E.style.height = $ - 31 + "px";
		                E.style.display = "block";
		                F.style.visibility = "visible";
		                F.style.left = B.offsetLeft - 1 + "px";
		                F.style.top = B.offsetTop + 29 + "px";
		                E.addEventListener("click",
		                function() {
		                    F.style.visibility = "hidden";
		                    E.style.display = "none";
		                },
		                false)
		            } else {
		                F.style.visibility = "hidden";
		                E.style.display = "none";
		            }
		        },
		        false);
		    }, false);
		}
		
		if(hostname.indexOf('i.hi.baidu.com') > -1)
		{
		    opera.addEventListener('AfterEvent.DOMContentLoaded', function(userJSEvent){
		        var aa = getElementById("get_more_links");
		
		        opera.addEventListener('BeforeEvent.click',function(e){
		            var t = e.event.target;
		            if(t == aa)
		            {
		                var A = $("#get_more_links").find("small");
		                if (A.hasClass("on")) {
		                    A.removeClass("on").addClass("off");
		                } else {
		                    A.removeClass("off").addClass("on");
		                }
		                $("#more_links").toggle();
		            }
		            else
		            {
		                var A = $("#get_more_links").find("small");
		                if (A.hasClass("on")) {
		                    A.removeClass("on").addClass("off");
		                }
		                $("#more_links").hide();
		            }
		
		        },false);
		
		    }, false);
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix search result page display issue of baidu.com\nFix links display inside searchbox - image.baidu....). See browser.js for details');
	} else if(hostname.indexOf('bbc.co.uk')!=-1 && pathname.match( /^\/mobile\// )){			// TWEETY-118, Mobile BBC should default to mobile view
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Mobile BBC should default to mobile view). See browser.js for details');
	} else if(hostname.indexOf('britishairways.')!=-1){			// 256172, britishairways.com hides calendar behind IFRAME
		opera.defineMagicFunction('CP_getCalendar', function(oReal, oThis){
		var cal = oReal.apply(oThis, slice.call(arguments, 2));
		end = cal.indexOf('</iframe>')+9;
		cal = cal.substring(end); 
		return cal; 
		}
		); 
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (britishairways.com hides calendar behind IFRAME). See browser.js for details');
	} else if(hostname.indexOf('chinatimes.com')>-1){			// UMAFINAL-1483, Prevent unexpected back navigation on chinatimes.com
		window.history.go=function(){};
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Prevent unexpected back navigation on chinatimes.com). See browser.js for details');
	} else if(hostname.indexOf('clearwire.com')!=-1){			// PIONER-268, PIONER-268 Flash on clearwire.com doesn't display on homepage
		opera.defineMagicVariable('flash', function(o){ o.embedMovie = function(swfFile,width,height,bgcolor,ver,altFormat,params) { s = '<embed src="'+swfFile+'" quality="high" type="application/x-shockwave-flash" swLiveConnect=true pluginspage="https://www.macromedia.com/go/getflashplayer" width=' + width + ' height=' + height + ' bgcolor="'+bgcolor+'"></embed>\n'; document.write(s); }; o.hasVersion=function(){return true;}; o.swf=true; return o;}, null);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (PIONER-268 Flash on clearwire.com doesn\'t display on homepage). See browser.js for details');
	} else if(hostname.indexOf('cs.kddi.com')>-1){			// PATCH-656, Fix disabled buttons on KDDI Customer Support page
		HTMLInputElement.prototype.__defineSetter__('disabled', function(){});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix disabled buttons on KDDI Customer Support page). See browser.js for details');
	} else if(hostname.indexOf('dcinside.com') > -1){			// SEOUL-22, Fixes having scrollbars appear when panning on dcinside.com
		addCssToDocument('body {overflow: visible} .favoriteDiv {overflow: visible} .dcMainAll {overflow: visible}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fixes having scrollbars appear when panning on dcinside.com). See browser.js for details');
	} else if(hostname.indexOf('digg.com')!=-1){			// PENGU-745, Can not login to digg.com
		        opera.addEventListener('BeforeExternalScript', function(e){
		            var oldua=navigator.userAgent;
		            navigator.userAgent = navigator.userAgent.replace( /Opera Mobi/, '' );
		            opera.addEventListener('AfterExternalScript',function(){
		                navigator.userAgent=oldua;
		            }, false);
		        },false);
		    
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Can not login to digg.com). See browser.js for details');
	} else if(hostname.indexOf('facebook.com')>-1){			// PATCH-410, Make share button on mobile facebook work
		opera.addEventListener( 'BeforeEventListener.click',function(e){
				if(e.event.__bjsFake)return;
				if( e.event.target.tagName=='LABEL' && e.event.target.className.indexOf('btn')>-1 && e.event.target.firstElementChild.type=='submit'){
					e.preventDefault();
					var evt=document.createEvent('Event');
					evt.initEvent('click', false, false);
					evt.__bjsFake=true;
					e.event.target.firstElementChild.dispatchEvent(evt);
				}
			},false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Make share button on mobile facebook work). See browser.js for details');
	} else if(hostname.indexOf('forever21.co.jp') > -1){			// PATCH-617, missing QuickView background color on Forever21.co.jp
		if (pathname.indexOf('QuickView.aspx')>-1) {
			addCssToDocument('html{background:#fff}');
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (missing QuickView background color on Forever21.co.jp). See browser.js for details');
	} else if(hostname.indexOf('frys.com')>-1){			// PATCH-638, frys.com: avoid racy framebuster due to lack of script async
		addPreprocessHandler('self.parent.location=document.location;','if(self!=top)self.parent.location=document.location;');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (frys.com: avoid racy framebuster due to lack of script async). See browser.js for details');
	} else if(hostname.indexOf('ganji.cn')>-1){			// NHSP-426, Fix touch version layout issue of 3g.ganji.com
		if((hostname.indexOf('3g.')>-1 && location.search.indexOf('vvcc=3g')>-1) || location.search.length < 1) {
			//NHSP-426 	  
			opera.addEventListener('BeforeCSS', function(userJSEvent){
				  userJSEvent.cssText = userJSEvent.cssText.replace(/-(moz|ms|webkit)-(linear-gradient|gradient|transform|transition|background-size|text-size-adjust|tap-highlight-color|touch-callout|appearance|animation|keyframes)/g,'-o-$2');
			}, false);
			
			opera.addEventListener('BeforeCSS', function(userJSEvent){
			  userJSEvent.cssText = userJSEvent.cssText.replace(/-(moz|ms|webkit)-(border|border-radius|border-top-left-radius|border-bottom-left-radius|border-top-right-radius|border-bottom-right-radius|text-overflow| box-shadow|box|box-sizing|box-pack|box-align|box-flex|box-orient)/g,'$2')
			}, false);
			
			//Opera Doesn't support display: box; box-flex: 1; 
			addCssToDocument('.gj-tab div {display:inline-block; width: 22.5%; } .gj-ntab-list div { display:inline-block; width: auto !important;  .gj-ntab-list div, .gj-ntab-index div { padding: 0px;} } .gj-footer-nav1 a  {display:inline-block; margin: 0px; padding: 0px 6px; } .gj-footer-nav2 a { display:inline-block; width: 40.5%; } .gj-footer-nav3 a { display:inline-block; width: 30%; } .gj-w-search {  background: -o-linear-gradient(top,#53AF00, #368F04); } ');
		}
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix touch version layout issue of 3g.ganji.com). See browser.js for details');
	} else if(hostname.indexOf('geoaccess.com')!=-1){			// 318050,  BlueCross browser sniffing prevents insurance search
		opera.defineMagicVariable('is_nav', function(){return true;}, null);
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( BlueCross browser sniffing prevents insurance search). See browser.js for details');
	} else if(hostname.indexOf('goo.ne.jp')>-1){			// PATCH-650, Fix search suggestions on Goo search engine
		HTMLElement.prototype.__defineGetter__('currentStyle', function(){})
		document.addEventListener('DOMContentLoaded',function(e){
			if (gooSuggest && typeof sgtObj == "undefined") {
				createSuggest();
			}
		},false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix search suggestions on Goo search engine). See browser.js for details');
	} else if(hostname.indexOf('gougou.com')>-1){			// YUSHAN-2457, Fixed gougou.com search button display issue
		addCssToDocument(".searchform .in_txt { width: 110px !important;} .searchform { width: 225px !important; }");
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fixed gougou.com search button display issue). See browser.js for details');
	} else if(hostname.indexOf('hao123.com')>-1){			// DONGDAE-3678, Make sure site accesses correct Flash instance for saved user data
		document.__defineGetter__('GlobalSharedObject', function(){ return document.getElementById('GlobalSharedObject'); });
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Make sure site accesses correct Flash instance for saved user data). See browser.js for details');
	} else if(hostname.indexOf('huntington.com')>-1){			// PATCH-712, huntington.com: work around browser sniff
		opera.defineMagicVariable('browserOkay',function(){return true},null);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (huntington.com: work around browser sniff). See browser.js for details');
	} else if(hostname.indexOf('jabong.com')>-1){			// PATCH-658, jabong.com: override usage of CSS content property on element content
		opera.addEventListener('BeforeCSS', function(e){
		  e.cssText = e.cssText.replace(/.clearfix:after,#content,#content:after,/g,'.clearfix:after,#content:after,');
		}, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (jabong.com: override usage of CSS content property on element content). See browser.js for details');
	} else if(hostname.indexOf('java.vnet.mobi')>-1){			// HMONY-1927, Remove overlapping text on vnet.mobi
		if( document.documentElement ){ 
		 var meta=document.documentElement.appendChild(document.createElement('meta')); 
		 meta.setAttribute('name', "viewport"); 
		 meta.setAttribute('content', "width=340,user-scalable=no");
		}
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Remove overlapping text on vnet.mobi). See browser.js for details');
	} else if(hostname.indexOf('m.deadspin.com')>-1){			// PATCH-655, Fix Gawker Media mobile site (Deadspin)
		fixGawkerMobile();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix Gawker Media mobile site (Deadspin)). See browser.js for details');
	} else if(hostname.indexOf('m.gawker.com')>-1){			// PATCH-655, Fix Gawker Media mobile site (Gawker)
		fixGawkerMobile();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix Gawker Media mobile site (Gawker)). See browser.js for details');
	} else if(hostname.indexOf('m.gizmodo.com')>-1){			// PATCH-655, Fix Gawker Media mobile site (Gizmodo)
		fixGawkerMobile();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix Gawker Media mobile site (Gizmodo)). See browser.js for details');
	} else if(hostname.indexOf('m.io9.com')>-1){			// PATCH-655, Fix Gawker Media mobile site (io9)
		fixGawkerMobile();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix Gawker Media mobile site (io9)). See browser.js for details');
	} else if(hostname.indexOf('m.jalopnik.com')>-1){			// PATCH-655, Fix Gawker Media mobile site (Jalopnik)
		fixGawkerMobile();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix Gawker Media mobile site (Jalopnik)). See browser.js for details');
	} else if(hostname.indexOf('m.jezebel.com')>-1){			// PATCH-655, Fix Gawker Media mobile site (Jezebel)
		fixGawkerMobile();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix Gawker Media mobile site (Jezebel)). See browser.js for details');
	} else if(hostname.indexOf('m.kotaku.com')>-1){			// PATCH-655, Fix Gawker Media mobile site (Kotaku)
		fixGawkerMobile();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix Gawker Media mobile site (Kotaku)). See browser.js for details');
	} else if(hostname.indexOf('m.lifehacker.com')>-1){			// PATCH-655, Fix Gawker Media mobile site (Lifehacker)
		fixGawkerMobile();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix Gawker Media mobile site (Lifehacker)). See browser.js for details');
	} else if(hostname.indexOf('m.reference.com')!=-1){			// TWEETY-107, Mobile reference.com uses generic doctype
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Mobile reference.com uses generic doctype). See browser.js for details');
	} else if(hostname.indexOf('m.weibo.cn')>-1){			// OMO-400, Fix m.weibo.cn screwed up issue
		addCssToDocument('.ctrea { clear:both; }');
				// NHSP-410, Fix friend thumbnails don't show in order of m.weibo.cn
		addCssToDocument('.user_ta .user_if { display:inline-block; margin-right: 4px; }');
				// NHSP-434, Original photo button display issue of m.weibo.cn
		addCssToDocument('.diack .btn { color: #fff !important; background-image: none !important; background: rgba(32, 32, 32, 0.6) !important; border: 0px !important; border: 1px solid #222; } ');
				// OMO-76, Fix focus issue on sina weibo log in page
		opera.defineMagicFunction('validat', 
		        function()
		        {
		            var d = document,
		            g = 'getElementById',
		            f = d[g]('form'),
		            o1 = d[g]('zh'),
		            o2 = d[g]('mm');
		            if (o1.value == "") {
		                alert("请输入账号！");
		                o1.focus();
		                return;
		            }
		            if (o2.value == "") {
		                alert("请输入密码！");
		                o2.focus();
		                return;
		            }
		            f.action = "login";
		            f.submit();
		        }
		    );
				// OMO-82, Fix issue of word account element is shown in incorrect place of sina weibo post view
		addCssToDocument('.faceico, .atico, .htico, .pos, .upload { width: 40px; !important; }');
				// OMO-86, Fix word account element display issue of sina weibo
		if(href.indexOf('m.weibo.cn/showpic')!=-1)
		{
			addCssToDocument("body .orgpic { background:-o-linear-gradient(top, #2074AF, #2C91D2) !important; }");
		}
				// OMO-83, Fix display issue of  'cleanup button'  in sina weibo
		addCssToDocument('.caico{ background: url(http://u1.sinaimg.cn/upload/h5/img/v4/ca.png) no-repeat center, -o-linear-gradient(#d1e9ff,#e7f4ff);border-radius: 0 3px 3px 0;!important;}');
				// OMO-129, Fix URL encoding issue of sina weibo
		/**
		*  Taken from third party:
		*  URL encode / decode
		*  http://www.webtoolkit.info/
		*
		**/
		function url_decode(url_str){
		        utftext = unescape(url_str);
		        var string = "";
		        var i = 0;
		        var c = c1 = c2 = 0; 
		
		        while ( i < utftext.length ) {
		                c = utftext.charCodeAt(i);
		
		                if (c < 128) {
		                        string += String.fromCharCode(c);
		                        i++;    
		                }       
		                else if((c > 191) && (c < 224)) { 
		                        c2 = utftext.charCodeAt(i+1);
		                        string += String.fromCharCode(((c & 31) << 6) | (c2 & 63)); 
		                        i += 2; 
		                }       
		                else {  
		                        c2 = utftext.charCodeAt(i+1);
		                        c3 = utftext.charCodeAt(i+2);
		                        string += String.fromCharCode(((c & 15) << 12) | ((c2 & 63) << 6) | (c3 & 63)); 
		                        i += 3; 
		                }       
		
		        }       
		        return string; 
		}
		
		    opera.defineMagicFunction('searchTopic',
		        function(origin_func, thisObject, c)
		        {
			    c[1] = url_decode(c[1]);
		            origin_func(c);
		        }
		    );
				// OMO-84, Fix  buttons of post view display issue in weibo.cn
		addCssToDocument('.fhs .return, .fhs .btn {background: -o-linear-gradient(#fff,#eaf5ff) !important;}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix m.weibo.cn screwed up issue\nFix friend thumbnails don\'t show in order of m.weibo.cn\nOriginal p...). See browser.js for details');
	} else if(hostname.indexOf('m.zdnet.com')!=-1){			// TWEETY-110, Mobile zdnet.com should be displayed in mobile view
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Mobile zdnet.com should be displayed in mobile view). See browser.js for details');
	} else if(hostname.indexOf('mail.live.com')!=-1){			// CORE-17447, Mispositioned sprites due to missing CSS
		addCssToDocument('.c_is { display: inline-block }');
				// UMAFINAL-1189, Fake designMode for Hotmail, hides rich text UI
		prepareFakeDesignMode();
		addCssToDocument('.ButtonList{display:none!important}');
				// DSK-235885, Hotmail uses lookupGetter on prototypes, not instances
		var styleSetterLookupMethod = document.createElement('span').style.__lookupSetter__;
		 CSSStyleDeclaration.prototype.__lookupSetter__ = function(prop){
			return styleSetterLookupMethod.call(document.createElement('span').style, prop);
		 };
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Mispositioned sprites due to missing CSS\nFake designMode for Hotmail, hides rich text UI\nHotmail u...). See browser.js for details');
	} else if(hostname.indexOf('mk.co.kr') > -1){			// 364762, mk.co.kr requests a lot of additional javascript after checking document.all - customer requested fix for load time
		document.all = undefined;
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (mk.co.kr requests a lot of additional javascript after checking document.all - customer requested fi...). See browser.js for details');
	} else if(hostname.indexOf('mobile.handango.com')!=-1){			// TWEETY-44, mobile.handango.com pages are displayed in overview mode, since they are declared without doctype.
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (mobile.handango.com pages are displayed in overview mode, since they are declared without doctype.). See browser.js for details');
	} else if(hostname.indexOf('mobile.orange.ch')!=-1){			// 357472, Fix for table align making tables behave as inline on mobile.orange.ch
		addCssToDocument('table{float:none; !important}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix for table align making tables behave as inline on mobile.orange.ch). See browser.js for details');
	} else if(hostname.indexOf('mobile.youporn.com')!=-1){			// TWEETY-109, Mobile youporn.com uses generic doctype
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Mobile youporn.com uses generic doctype). See browser.js for details');
	} else if(hostname.indexOf('moneta.co.kr')!=-1){			// SEOUL-618, Renames method on moneta.co.kr (was named goto), also hides flash advertisements that cover content
		window.opera.addEventListener('BeforeScript', function(e) {
		e.element.text = e.element.text.replace(
				  /function goto\(/g,
				  'function moneta_co_kr_goto('
				);
		}, false);
		
		window.opera.addEventListener(
			    'BeforeJavascriptURL',
			    function (e) {
			      if( e.source.indexOf('goto') != -1 ) {
				
				e.source = e.source.replace(
				  /goto\(/g,
				  'moneta_co_kr_goto('
				);
			      }
			    },
			    false
			  );
		
				// SEOUL-466, Gets rid of flash that is mispositioned on moneta.co.kr
		opera.addEventListener('BeforeExternalScript', function(e){
		preventDefault.call=indexOf.call=call; if(e.element.src && indexOf.call(e.element.src, 'ad.moneta.co.kr')!=-1){preventDefault.call(e);}}, false);
				// OTW-4374, Hides background image in search bar on moneta.co.kr
		opera.defineMagicFunction('searchCheck', function() { document.getElementsByName('kwd')[0].style.background = 'none';});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Renames method on moneta.co.kr (was named goto), also hides flash advertisements that cover content\...). See browser.js for details');
	} else if(hostname.indexOf('myapp.com')>-1){			// NHSP-424, Navigation part display issue of myapp.com
		addCssToDocument('header.main > nav ul li { display:inline-block; margin-right: 2px; padding: 0px 6px;}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Navigation part display issue of myapp.com). See browser.js for details');
	} else if(hostname.indexOf('myspace.com')>-1){			// EMO-4049, Enable log in to myspace
		HTMLInputElement.prototype.__defineSetter__('type',function(v){
			if (this.type!==v) {
				var doFocus = (this == document.activeElement);
				this.setAttribute('type',v);
				if (doFocus) this.focus();
				return v;
			}
		});
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Enable log in to myspace). See browser.js for details');
	} else if(hostname.indexOf('netian.com')>-1){			// 354018, Moves the absolutely positioned SMS div on netian.com (after logging in)
		addCssToDocument('#closer { position: relative !important }');
		addCssToDocument('#hd { position: relative !important }');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Moves the absolutely positioned SMS div on netian.com (after logging in)). See browser.js for details');
	} else if(hostname.indexOf('netpia.linkprice.com')>-1){			// 354340, Clears popups that are visible after loading subpages on netpia.linkprice.com
		addEventListener.call(document, 'load', function(){try{clear()}catch(e){}}, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Clears popups that are visible after loading subpages on netpia.linkprice.com). See browser.js for details');
	} else if(hostname.indexOf('o2active')!=-1){			// 266967, o2active.de, making sure narrow centered column does not appear off-screen
		addCssToDocument('body{width:100%!important; max-width:'+screen.width+'px;}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (o2active.de, making sure narrow centered column does not appear off-screen). See browser.js for details');
	} else if(hostname.indexOf('opera.com')>-1&& pathname.indexOf('/docs/browserjs/')==0){			// 0, Browser.js status and version reported on browser.js documentation page
		document.addEventListener((parseFloat(opera.version())>9?'DOMContentLoaded':'load'),function(){
			if(document.getElementById('browserjs_active')){
				document.getElementById('browserjs_active').style.display='';
				document.getElementById('browserjs_active').getElementsByTagName('span')[0].appendChild(document.createTextNode(bjsversion));
				document.getElementById('browserjs_status_message').style.display='none';
			}else if(document.getElementById('browserjs_status_message')){
				document.getElementById('browserjs_status_message').firstChild.data='Browser.js is enabled! '+bjsversion;
			}
		}, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Browser.js status and version reported on browser.js documentation page). See browser.js for details');
	} else if(hostname.indexOf('ota.getvzappzone.com')!=-1){			// TWEETY-192, Verizon Wireless mobile app zone site should default to mobile view
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Verizon Wireless mobile app zone site should default to mobile view). See browser.js for details');
	} else if(hostname.indexOf('pb.yamada-denki.jp')>-1){			// PATCH-202, Show digital pamphlet from Yamada Denki
		Element.prototype.attachEvent = null;
		window.opera = null;
		document.addEventListener('DOMContentLoaded',function(e){
			document.addEventListener('mousewheel',onMouseWheel,true);
		},false);
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Show digital pamphlet from Yamada Denki). See browser.js for details');
	} else if(hostname.indexOf('phim88.com')>-1){			// SOKRI4-1002, "Close overlay ad before playing film" does not work with a window-level plugin implementation
		// phim88.com code uses LTAS object
		opera.defineMagicVariable('LTAS', function(obj){
			var origOverlayCloseandPlay=obj.OverlayCloseandPlay;
			obj.OverlayCloseandPlay=function(playerid){
				document.getElementById(playerid).style.visibility='visible';
				return origOverlayCloseandPlay.apply(this, arguments);
			}
			var origShowAd=obj.ShowAd;
			obj.ShowAd=function(playerid, ad){
				document.getElementById(playerid).style.visibility='hidden';
				return origShowAd.apply(this, arguments);
			};
			return obj;
		}, null);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ("Close overlay ad before playing film" does not work with a window-level plugin implementation). See browser.js for details');
	} else if(hostname.indexOf('photobucket.com')>-1){			// YUSHAN-293, Fix overlapped header text for photobucket.com
		addCssToDocument(" div.featuredPromo h1, div.featuredPromo h3 { white-space:nowrap !important; }"); 
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix overlapped header text for photobucket.com). See browser.js for details');
	} else if(hostname.indexOf('rr.com') != -1 || hostname.indexOf('roadrunner.com') != -1){			// PIONER-353, Text-shadow not properly specified on rr.com
		addCssToDocument("a.btnXLRed span, .header .content .menu li a{text-shadow:none !important;}");
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Text-shadow not properly specified on rr.com). See browser.js for details');
	} else if(hostname.indexOf('samsungmobileusa.com')>-1){			// PIONER-271, Samsung USA flash detection fix
		addPreprocessHandler(/9\.0\.115\.0/, '9.1.125.0' );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Samsung USA flash detection fix). See browser.js for details');
	} else if(hostname.indexOf('sayclub.com')>-1){			// 363232, hides id and password background images that are text input backgrounds
		document.addEventListener('DOMFocusIn', function(e){if(e.target.tagName=='INPUT'){
			e.target.style.backgroundImage = 'none';
			e.target.addEventListener('keypress', function(){ this.style.backgroundImage='none'; },false);
		}},true);
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (hides id and password background images that are text input backgrounds). See browser.js for details');
	} else if(hostname.indexOf('sinaapp.com') > -1){			// NHSP-425, Draw game contents missing issue of sinaapp.com
		if (hostname.indexOf('iavadraw') > -1 && pathname.indexOf('draw') >-1) {
		 addCssToDocument('.gamelistb2in { width: 96px !important; }'); 
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Draw game contents missing issue of sinaapp.com). See browser.js for details');
	} else if(hostname.indexOf('siren24.com')!=-1){			// SEOUL-609, ActiveX installation page redirect on siren24.com due to sniffing limitation on redirect script
		navigator.appName = 'Netscape';
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (ActiveX installation page redirect on siren24.com due to sniffing limitation on redirect script). See browser.js for details');
	} else if(hostname.indexOf('smithbarney.com')>-1){			// PATCH-360, Enable the password box on smithbarney.com
		HTMLInputElement.prototype.__defineSetter__('type',function(){
			if (this.getAttribute('type')!=arguments[0]) {
				var doFocus=false, result;
				if (this == document.activeElement) doFocus = true;
				result = this.setAttribute('type',arguments[0]);
				if (doFocus) this.focus();
				return result;
			}
		});
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Enable the password box on smithbarney.com). See browser.js for details');
	} else if(hostname.indexOf('sperrysoftware.com')!=-1){			// 309189, Nested tables with 100% height are not laid out as expected, menu is pushed down
		addCssToDocument('td{vertical-align:top}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Nested tables with 100% height are not laid out as expected, menu is pushed down). See browser.js for details');
	} else if(hostname.indexOf('sports.donga.com')>-1){			// 354059, Blocks floating flash ad on sports.donga.com that cannot be closed
		addCssToDocument('#FloatLayer1{visibility:hidden!important}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Blocks floating flash ad on sports.donga.com that cannot be closed). See browser.js for details');
	} else if(hostname.indexOf('star.moneytoday.co.kr')>-1){			// 348222, Clicks on a link to display the front page story in an iframe on star.moneytoday.co.kr
		try {
		    addEventListener.call(document, 'DOMContentLoaded', function(){
		        var elm=document.getElementById('realtimenews');
		        if(elm){
		            elm.childNodes[1].childNodes[1].childNodes[0].click();
		        }
		    }, false);
		} catch(e) {}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Clicks on a link to display the front page story in an iframe on star.moneytoday.co.kr). See browser.js for details');
	} else if(hostname.indexOf('t.yuuquu.com')>-1){			// OMO-104, Fix log in issue of t.yuuquu.com
		if(pathname.toLowerCase().indexOf('tologin')>-1){
		document.addEventListener('DOMContentLoaded', function(){
					var ipt = document.getElementsByTagName("input");
					for(var i=0; i< ipt.length; i++) {
						if(ipt[i].getAttribute('type')=='tel' || ipt[i].getAttribute('type')=='password'){
							 ipt[i].setAttribute('onfocus','');
						}	
					}			
				}, false);	
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix log in issue of t.yuuquu.com). See browser.js for details');
	} else if(hostname.indexOf('taobao.com')>-1){			// NHSP-435, Fix layout messing up issue of m.taobao.com touch screen version
		if(hostname.indexOf('m.')>-1 || hostname.indexOf('wap.')>-1 ) {
			 if(location.search.indexOf('v=1')<=-1 && (pathname.length <2 && (location.search.length <2 || location.search.indexOf('sprefer=sypc00')>-1))) {
				location.replace('http://m.taobao.com/?v=1');
			 }
			 if(location.search.indexOf('v=1')>-1) {
				 //Remove Touch version links
				addCssToDocument('.vision, .website-nav a font[color=gray] {display: none;}'); 
			 }
		}
				// OMO-267, Fix input box and layout display issue of login.m.taobao.com
		if(hostname.indexOf('m.')>-1 || hostname.indexOf('wap.')>-1 ) {
			if(pathname.indexOf('login')>-1 && hostname.indexOf('login')>-1)
			{
				addCssToDocument('.login .login-form li {height:auto !important;} .common-btn-full {background: -o-linear-gradient(#F94920,#EB3E13) !important;}');
			}
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix layout messing up issue of m.taobao.com touch screen version\nFix input box and layout display i...). See browser.js for details');
	} else if(hostname.indexOf('time.com')>-1){			// 229826, time.com script causes reload loop if UA contains "Windows CE"
		navigator.userAgent=navigator.userAgent.replace( /windows ce/i, '' );
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (time.com script causes reload loop if UA contains "Windows CE"). See browser.js for details');
	} else if(hostname.indexOf('tistory.com')!=-1){			// 347990, two login buttons on tistory.com
		addCssToDocument('#memberbox .btn-login {text-indent:-100px;}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (two login buttons on tistory.com). See browser.js for details');
	} else if(hostname.indexOf('twitter.com')>-1 && pathname.length <2){			// YUSHAN-294, Fix search button and search box overlap issue for twitter.com
		addCssToDocument("#home_search p { white-space:nowrap !important;  }"); 
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix search button and search box overlap issue for twitter.com). See browser.js for details');
	} else if(hostname.indexOf('viacom.com')!=-1){			// SEOUL-616, Tweaked SWFObject on viacom.com creates constant document reflows
		opera.defineMagicVariable('plugin', function(curVal) { return true; }, null);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Tweaked SWFObject on viacom.com creates constant document reflows). See browser.js for details');
	} else if(hostname.indexOf('wap.flycell.com.br')!=-1){			// SOKRI3-1432, Avoid CSS input validation of hidden inputs
		addCssToDocument('input[type=hidden], input[type=submit]{-wap-input-format: "*m" !important;}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Avoid CSS input validation of hidden inputs). See browser.js for details');
	} else if(hostname.indexOf('wap.playboy.com')==0){			// SOKRI4-1550, Resize home banner and other wide images
		addCssToDocument( 'img{max-width: '+(screen.width)+'px; }' );
		document.addEventListener('DOMContentLoaded', function(){
			var largeImgs=document.selectNodes('//img[@width>'+window.innerWidth+']');
			for(var i=0,img;img=largeImgs[i];i++){
				var scalingFactor = window.innerWidth/(img.width+15);//add 15 px for scroll bar and such
				img.style.width=(img.width*scalingFactor)+'px';
				img.style.height=(img.height*scalingFactor)+'px';
			}
		}, false);
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Resize home banner and other wide images). See browser.js for details');
	} else if(hostname.indexOf('wap.sina.com')>-1){			// YUSHAN-2339, Fix line-height issue of wap.sina.com.cn
		addCssToDocument("body {line-height: 1.5em;}");
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix line-height issue of wap.sina.com.cn). See browser.js for details');
	} else if(hostname.indexOf('wap.smartone-vodafone.com')>-1){			// SOKRI3-1645, Re-initialize page on back to make plugins work correctly
		opera.setOverrideHistoryNavigationMode('compatible');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Re-initialize page on back to make plugins work correctly). See browser.js for details');
	} else if(hostname.indexOf('wap.vnet.mobi')>-1){			// HMONY-1927, Remove overlapping text on vnet.mobi
		if( document.documentElement ){ 
		 var meta=document.documentElement.appendChild(document.createElement('meta')); 
		 meta.setAttribute('name', "viewport"); 
		 meta.setAttribute('content', "width=340,user-scalable=no");
		}
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Remove overlapping text on vnet.mobi). See browser.js for details');
	} else if(hostname.indexOf('wapp.verizon.net')!=-1){			// OSAN-11, Verizon mobile webmail service should default to mobile view
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Verizon mobile webmail service should default to mobile view). See browser.js for details');
	} else if(hostname.indexOf('webprint.post.japanpost.jp')>-1){			// PATCH-449, japanpost.jp: Fix broken _supportsDOM function
		opera.defineMagicFunction('_supportsDOM',function (oReal,oThis) { return true; });
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (japanpost.jp: Fix broken _supportsDOM function). See browser.js for details');
	} else if(hostname.indexOf('westjet.com')>-1 ){			// PATCH-260,  Westjet browser sniffing warns against Opera
		opera.defineMagicVariable('browser', function(o){ o.isSupported=true; return o; }, null);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( Westjet browser sniffing warns against Opera). See browser.js for details');
	} else if(hostname.indexOf('www.answers.com')>-1){			// PATCH-719, answers.com: add background gradient
		addCssToDocument('body{background-image: -o-linear-gradient(top,rgba(74,114,193,0.98),rgba(31,56,105,0.98)), url(http://en.site2.answcdn.com/templates/images/stripe.png?v=49d225d);}');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (answers.com: add background gradient). See browser.js for details');
	} else if(hostname.indexOf('xuan.3g.cn')>-1){			// OMO-89, Fix page layout issues on 3G.cn
		addCssToDocument('.navMain p a {width:16% !important; } .screen-gt320 h1, .screen-gt320 h1 a { font-size: 16px !important;  }');
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Fix page layout issues on 3G.cn). See browser.js for details');
	} else if(hostname.indexOf('yoyaku.rakubus.jp')>-1){			// PATCH-559, Browser sniffing on Raku Bus
		navigator.appName = 'Microsoft '+navigator.appName;
		navigator.appVersion = 'MSIE 9.0; '+navigator.appVersion;
		navigator.userAgent = 'MSIE 9.0; '+navigator.userAgent;
		
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Browser sniffing on Raku Bus). See browser.js for details');
	} else if(hostname=='live.vodafone.com'&&pathname.indexOf('/jumppage')==0){			// 362160, Display Vodafone's Google search site in Normal Zoom by default
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Display Vodafone\'s Google search site in Normal Zoom by default). See browser.js for details');
	} else if(hostname=='m.espn.go.com'){			// OSAN2-282, Content goes over screen width on m.espn.go.com
		scaleImagesToScreenWidth();
		forceWordWrapping();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Content goes over screen width on m.espn.go.com). See browser.js for details');
	} else if(hostname=='mobile.vzwapp.com' || hostname=='mobile.vzw.com' || hostname=='start.vzw.com'){			// OSAN-227, VZW mobile start page has colored span elements that overlap images
		if(location.pathname=='/')addCssToDocument('span{background: none !important;}');
				// 356069, VZW mobile portal does not trigger mobile view
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (VZW mobile start page has colored span elements that overlap images\nVZW mobile portal does not trig...). See browser.js for details');
	} else if(hostname=='wap.smart.com.ph'){			// 327422,  WAP site on smart.com.ph serves XHTML content without xmlns
		document.addEventListener('DOMContentLoaded',function (){
			if(!document.body && document.documentElement.nodeName == 'html' && document.documentElement.namespaceURI == null){
				document.replaceChild(	(new DOMParser()).parseFromString(((new XMLSerializer()).serializeToString(document)).replace(/<html/,'<html xmlns="http://www.w3.org/1999/xhtml"'),'application/xml').documentElement, document.documentElement);
			}
		}, false );
		
				// 331879, Automatically re-parse XHTML content with parse errors as HTML
		document.addEventListener('DOMContentLoaded', function(e){
			if(document.links[0].href=='opera:forcehtml'){ document.links[0].click(); }
		}, false);
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' ( WAP site on smart.com.ph serves XHTML content without xmlns\nAutomatically re-parse XHTML content w...). See browser.js for details');
	} else if(hostname=='weather-mobile.weatherbug.com'){			// OSAN2-283, Banner goes over screen width on weather-mobile.weatherbug.com
		scaleImagesToScreenWidth(); 
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (Banner goes over screen width on weather-mobile.weatherbug.com). See browser.js for details');
	} else if(hostname=='xhtml.emome.net'){			// 328103, emome.net wap portal does not trigger mobile view
		forceMobileView();
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (emome.net wap portal does not trigger mobile view). See browser.js for details');
	} else if(href == 'http://www.dowwallpaper.com/index.htm'){			// UMAFINAL-1521, redirect to frame content to prevent rendering error for small buffer size
		window.location.replace("home.php");
			if(self==top)postError.call(opera, 'Opera has modified the JavaScript on '+hostname+' (redirect to frame content to prevent rendering error for small buffer size). See browser.js for details');
	}

})(opera);
